/*
 * LoadAthletesPanel.java
 *
 */

package net.azib.java.students.t060401.homework.gui;

import net.azib.java.students.t060401.homework.decathlon.DecathlonDao;
import net.azib.java.students.t060401.homework.decathlon.DecathlonInfoVector;
import net.azib.java.students.t060401.homework.decathlon.model.CompetitionVO;
import net.azib.java.students.t060401.homework.util.LanguageUtil;

import java.io.File;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;
import javax.swing.GroupLayout;
import javax.swing.JFileChooser;
import javax.swing.LayoutStyle;

/**
 * Panel with components loading decathlon data from file or database.
 *
 * @author t060401
 */
public class LoadAthletesPanel extends javax.swing.JPanel {
    
	/** serialVersionUID */
	private static final long serialVersionUID = 1L;
	
	DecathlonInfoVector decathlonVector;
	
    /** Creates new form LoadAthletesPanel */
    public LoadAthletesPanel(DecathlonInfoVector decathlonVector) {
    	this.decathlonVector = decathlonVector;
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
    	swingFileDialog = new JFileChooser();
    	
        openFileButton = new javax.swing.JButton();
        openDBDataButton = new javax.swing.JButton();
        chooseCompetitionCombo = new javax.swing.JComboBox();
        infoLabel = new javax.swing.JLabel();

        openFileButton.setText(LanguageUtil.getString("LoadAthletes.LoadFromFile"));
        openFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openFileButtonMouseClicked(evt);
            }
        });

        openDBDataButton.setText(LanguageUtil.getString("LoadAthletes.LoadFromDB"));
        openDBDataButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                openDBDataButtonMouseClicked(evt);
            }
        });

        infoLabel.setText(LanguageUtil.getString("LoadAthletes.InfoMsg"));
        
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        
        GroupLayout layout = new GroupLayout(this);  
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(openFileButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(infoLabel, GroupLayout.DEFAULT_SIZE, 97, Short.MAX_VALUE)
                        .addContainerGap(278, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING, false)
                            .addComponent(chooseCompetitionCombo, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(openDBDataButton, GroupLayout.DEFAULT_SIZE, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(infoLabel)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openFileButton)
                .addGap(15, 15, 15)
                .addComponent(chooseCompetitionCombo, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openDBDataButton)
                .addContainerGap(176, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openDBDataButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openDBDataButtonMouseClicked
    	infoLabel.setText("");
		Object selectedItem = chooseCompetitionCombo.getSelectedItem();
		if (selectedItem instanceof CompetitionVO) {
			CompetitionVO selectedCompetition = (CompetitionVO) selectedItem;
			long competitionId = selectedCompetition.getId();
			String msg = decathlonVector.loadDecathlonInfoFromDB(competitionId);
			infoLabel.setText(msg);
		}
		else {
			infoLabel.setText(LanguageUtil.getString("LoadAthletes.NoCompetition"));
		}
    }// GEN-LAST:event_openDBDataButtonMouseClicked

    private void openFileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_openFileButtonMouseClicked
    	swingFileDialog.setFileFilter(new FileFilter());
		int returnVal = swingFileDialog.showOpenDialog(this);
		this.repaint();
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File selectedFile = swingFileDialog.getSelectedFile();
			String s = selectedFile.getPath();
			try {
				String msg = this.decathlonVector.loadDecathlonInfoFromFile(s);
				infoLabel.setText(msg);
			} catch (Exception e) {
				infoLabel.setText(e.getMessage());
			}
		}
    }//GEN-LAST:event_openFileButtonMouseClicked
    
    private void formComponentShown(java.awt.event.ComponentEvent evt) {
    	 Vector<Object> competitions = DecathlonDao.getCompetitions();
         competitions.add(0, LanguageUtil.getString("LoadAthletes.ChooseCompetition"));
         chooseCompetitionCombo.setModel(new DefaultComboBoxModel(competitions));
         
		infoLabel.setText("");
	}
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox chooseCompetitionCombo;
    private javax.swing.JLabel infoLabel;
    private javax.swing.JButton openDBDataButton;
    private javax.swing.JButton openFileButton;
    
    private JFileChooser swingFileDialog;
    // End of variables declaration//GEN-END:variables
    
}
