/*
 * ResultsPanel.java
 */

package net.azib.java.students.t060401.homework.gui;

import net.azib.java.students.t060401.homework.decathlon.DecathlonInfoVector;
import net.azib.java.students.t060401.homework.util.Constants;

import java.io.File;
import java.util.Arrays;
import java.util.Vector;

import javax.swing.GroupLayout;
import javax.swing.JFileChooser;

/**
 * Panel with components for showing decathlon data table and saving it into a file.
 *
 * @author t060401
 */
public class ResultsPanel extends javax.swing.JPanel {

	/** serialVersionUID */
	private static final long serialVersionUID = 1L;

	private static String[] tableHeader = new String[] { "Place", "Points", "Name", "Birth date", "Country",
			Constants.SPRINT_100M, Constants.LONG_JUMP, Constants.SHOT_PUT, Constants.HIGH_JUMP, Constants.SPRINT_400M,
			Constants.HURDLES_110M, Constants.DISCUS_THROW, Constants.POLE_VAULT, Constants.JAVELIN_THROW, Constants.RACE_1500M };

	DecathlonInfoVector decathlonVector;

	/** Creates new form ResultsPanel */
	public ResultsPanel(DecathlonInfoVector decathlonVector) {
		this.decathlonVector = decathlonVector;
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// <editor-fold defaultstate="collapsed" desc=" Generated Code
	// ">//GEN-BEGIN:initComponents
	private void initComponents() {
		swingFileDialog = new JFileChooser();
		
		jScrollPane1 = new javax.swing.JScrollPane();
		resultsTable = new javax.swing.JTable();
		saveFileButton = new javax.swing.JButton();
		clearResultsButton = new javax.swing.JButton();

		addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
		
		resultsTable.setModel(new javax.swing.table.DefaultTableModel(
				decathlonVector.toSortedVector(), new Vector<String>(Arrays.asList(tableHeader) )));
				// decathlonVector.toSortedArray(), tableHeader));

		resultsTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
		
		jScrollPane1.setViewportView(resultsTable);

		saveFileButton.setText("Save results to file");
		saveFileButton.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				saveFileButtonMouseClicked(evt);
			}
		});

		clearResultsButton.setText("Clear results");
        clearResultsButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearResultsButtonMouseClicked(evt);
            }
        });
            
       GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1,GroupLayout.DEFAULT_SIZE,GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(saveFileButton)
                        .addGap(21, 21, 21)
                        .addComponent(clearResultsButton)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(saveFileButton)
                    .addComponent(clearResultsButton))
                .addGap(8, 8, 8)
                .addComponent(jScrollPane1,GroupLayout.DEFAULT_SIZE, 247, Short.MAX_VALUE)
                .addContainerGap())
        );
    }
	
	private void clearResultsButtonMouseClicked(java.awt.event.MouseEvent evt) {
		decathlonVector.clear();
		reloadTable();
	}

	private void saveFileButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_saveFileButtonMouseClicked
		System.out.println("heihei");
		int returnVal = swingFileDialog.showSaveDialog(this);
		this.repaint();
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File selectedFile = swingFileDialog.getSelectedFile();
			String filePath = selectedFile.getPath();

			if (decathlonVector!=null)
			{
				decathlonVector.saveDecathlonInfoVector(filePath);
			}
		}
	}// GEN-LAST:event_saveFileButtonMouseClicked

	private void formComponentShown(java.awt.event.ComponentEvent evt) {
		reloadTable();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JTable resultsTable;
	private javax.swing.JButton saveFileButton;
	private javax.swing.JButton clearResultsButton;
	private JFileChooser swingFileDialog;

	// End of variables declaration//GEN-END:variables

	private void reloadTable() {
		Vector<String> headerVector = new Vector<String>(Arrays
						.asList(tableHeader));
		resultsTable.setModel(new javax.swing.table.DefaultTableModel(decathlonVector.toSortedVector(), headerVector));
	}
}
