package net.azib.java.students.t107110.homework;

/**
 * @author Eduard Shustrov
 */
enum Message {
	NO_INPUT, NO_INPUT_FILE, INPUT_FILE_NOT_FOUND, NO_EVENT, INPUT_NOT_SUPPORTED, UNKNOWN_INPUT,
	NO_OUTPUT, NO_OUTPUT_FILE, OUTPUT_NOT_SUPPORTED, UNKNOWN_OUTPUT,
	TOO_MANY_ARGS,
	NO_ATHLETE_NAME, NO_BIRTHDAY, NO_COUNTRY, NOT_ISO2_COUNTRY,
	NO_SPRINT_100M, NO_LONG_JUMP, NO_SHOT_PUT, NO_HIGH_JUMP, NO_SPRINT_400M,
	NO_HURDLES_110M, NO_DISCUS_THROW, NO_POLE_VAULT, NO_JAVELIN_THROW, NO_RACE_1500M,
	INCOMPLETE_RESULT, TOO_MUCH_DATA, WRONG_DATA_FORMAT,
	CANNOT_READ, CANNOT_INIT_WRITING, CANNOT_WRITE
}
