package net.azib.java.students.t107110.homework;

/**
 * @author
 */
enum Message {
	NO_INPUT, NO_INPUT_FILE, NO_COMPETITION, UNKNOWN_INPUT,
	NO_OUTPUT, NO_OUTPUT_FILE, UNKNOWN_OUTPUT,
	TOO_MANY_ARGS,
	NO_ATHLETE_NAME, NO_BIRTHDAY, NO_COUNTRY, NOT_ISO2_COUNTRY,
	NO_LONG_JUMP, NO_SHOT_PUT, NO_HIGH_JUMP, NO_SPRINT_400M, NO_HURDLES_110M,
	NO_DISCUS_THROW, NO_POLE_VAULT, NO_JAVELIN_THROW, NO_RACE_1500M, NO_SPRINT_100M,
	INCOMPLETE_RESULT, TOO_MUCH_DATA, WRONG_DATA_FORMAT
}
