//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.29 at 11:22:52 PM EEST 
//


package net.azib.java.students.t040750.homework.parser.xml;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for DecathlonType complex type, the root element of the XML representation 
 * of the output data.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecathlonType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DecathlonData" type="{}DecathlonDataType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecathlonType", propOrder = {
    "decathlonData"
})
public class DecathlonType {

    @XmlElement(name = "DecathlonData", required = true)
    protected List<DecathlonDataType> decathlonData;

    /**
     * Gets the value of the decathlonData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the decathlonData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDecathlonData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DecathlonDataType }
     * 
     * 
     */
    public List<DecathlonDataType> getDecathlonData() {
        if (decathlonData == null) {
            decathlonData = new ArrayList<DecathlonDataType>();
        }
        return this.decathlonData;
    }

}
