//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.29 at 11:22:52 PM EEST 
//


package net.azib.java.students.t040750.homework.parser.xml;

import net.azib.java.students.t040750.homework.generic.DecathlonData;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for DecathlonDataType complex type, the XML equivalent of the {@link DecathlonData} class.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DecathlonDataType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Position" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Athlete" type="{}AthleteType"/>
 *         &lt;element name="Result" type="{}ResultType"/>
 *         &lt;element name="TotalPoints" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DecathlonDataType", propOrder = {
    "position",
    "athlete",
    "result",
    "totalPoints"
})
public class DecathlonDataType {

    @XmlElement(name = "Position", required = true)
    protected String position;
    @XmlElement(name = "Athlete", required = true)
    protected AthleteType athlete;
    @XmlElement(name = "Result", required = true)
    protected ResultType result;
    @XmlElement(name = "TotalPoints")
    protected long totalPoints;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPosition(String value) {
        this.position = value;
    }

    /**
     * Gets the value of the athlete property.
     * 
     * @return
     *     possible object is
     *     {@link AthleteType }
     *     
     */
    public AthleteType getAthlete() {
        return athlete;
    }

    /**
     * Sets the value of the athlete property.
     * 
     * @param value
     *     allowed object is
     *     {@link AthleteType }
     *     
     */
    public void setAthlete(AthleteType value) {
        this.athlete = value;
    }

    /**
     * Gets the value of the result property.
     * 
     * @return
     *     possible object is
     *     {@link ResultType }
     *     
     */
    public ResultType getResult() {
        return result;
    }

    /**
     * Sets the value of the result property.
     * 
     * @param value
     *     allowed object is
     *     {@link ResultType }
     *     
     */
    public void setResult(ResultType value) {
        this.result = value;
    }

    /**
     * Gets the value of the totalPoints property.
     * 
     */
    public long getTotalPoints() {
        return totalPoints;
    }

    /**
     * Sets the value of the totalPoints property.
     * 
     */
    public void setTotalPoints(long value) {
        this.totalPoints = value;
    }

}
