//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.29 at 11:22:52 PM EEST 
//


package net.azib.java.students.t040750.homework.parser.xml;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Decathlon_QNAME = new QName("", "Decathlon");

    public ObjectFactory() {
    }

    public DecathlonDataType createDecathlonDataType() {
        return new DecathlonDataType();
    }

    public DecathlonType createDecathlonType() {
        return new DecathlonType();
    }

    public AthleteType createAthleteType() {
        return new AthleteType();
    }

    public ResultType createResultType() {
        return new ResultType();
    }

    @XmlElementDecl(namespace = "", name = "Decathlon")
    public JAXBElement<DecathlonType> createDecathlon(DecathlonType value) {
        return new JAXBElement<DecathlonType>(_Decathlon_QNAME, DecathlonType.class, null, value);
    }

}
