//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.05.29 at 11:22:52 PM EEST 
//


package net.azib.java.students.t040750.homework.parser.xml;

import net.azib.java.students.t040750.homework.generic.Result;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>Java class for ResultType complex type, the XML equivalent of the {@link Result} class.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ResultType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Run100m" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="LongJump" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="ShotPut" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="HighJump" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Run400m" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Hurdles110m" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Discus" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="PoleVault" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Javelin" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *         &lt;element name="Run1500m" type="{http://www.w3.org/2001/XMLSchema}float"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ResultType", propOrder = {
    "run100M",
    "longJump",
    "shotPut",
    "highJump",
    "run400M",
    "hurdles110M",
    "discus",
    "poleVault",
    "javelin",
    "run1500M"
})
public class ResultType {

    @XmlElement(name = "Run100m")
    protected float run100M;
    @XmlElement(name = "LongJump")
    protected float longJump;
    @XmlElement(name = "ShotPut")
    protected float shotPut;
    @XmlElement(name = "HighJump")
    protected float highJump;
    @XmlElement(name = "Run400m")
    protected float run400M;
    @XmlElement(name = "Hurdles110m")
    protected float hurdles110M;
    @XmlElement(name = "Discus")
    protected float discus;
    @XmlElement(name = "PoleVault")
    protected float poleVault;
    @XmlElement(name = "Javelin")
    protected float javelin;
    @XmlElement(name = "Run1500m")
    protected float run1500M;

    /**
     * Gets the value of the run100M property.
     * 
     */
    public float getRun100M() {
        return run100M;
    }

    /**
     * Sets the value of the run100M property.
     * 
     */
    public void setRun100M(float value) {
        this.run100M = value;
    }

    /**
     * Gets the value of the longJump property.
     * 
     */
    public float getLongJump() {
        return longJump;
    }

    /**
     * Sets the value of the longJump property.
     * 
     */
    public void setLongJump(float value) {
        this.longJump = value;
    }

    /**
     * Gets the value of the shotPut property.
     * 
     */
    public float getShotPut() {
        return shotPut;
    }

    /**
     * Sets the value of the shotPut property.
     * 
     */
    public void setShotPut(float value) {
        this.shotPut = value;
    }

    /**
     * Gets the value of the highJump property.
     * 
     */
    public float getHighJump() {
        return highJump;
    }

    /**
     * Sets the value of the highJump property.
     * 
     */
    public void setHighJump(float value) {
        this.highJump = value;
    }

    /**
     * Gets the value of the run400M property.
     * 
     */
    public float getRun400M() {
        return run400M;
    }

    /**
     * Sets the value of the run400M property.
     * 
     */
    public void setRun400M(float value) {
        this.run400M = value;
    }

    /**
     * Gets the value of the hurdles110M property.
     * 
     */
    public float getHurdles110M() {
        return hurdles110M;
    }

    /**
     * Sets the value of the hurdles110M property.
     * 
     */
    public void setHurdles110M(float value) {
        this.hurdles110M = value;
    }

    /**
     * Gets the value of the discus property.
     * 
     */
    public float getDiscus() {
        return discus;
    }

    /**
     * Sets the value of the discus property.
     * 
     */
    public void setDiscus(float value) {
        this.discus = value;
    }

    /**
     * Gets the value of the poleVault property.
     * 
     */
    public float getPoleVault() {
        return poleVault;
    }

    /**
     * Sets the value of the poleVault property.
     * 
     */
    public void setPoleVault(float value) {
        this.poleVault = value;
    }

    /**
     * Gets the value of the javelin property.
     * 
     */
    public float getJavelin() {
        return javelin;
    }

    /**
     * Sets the value of the javelin property.
     * 
     */
    public void setJavelin(float value) {
        this.javelin = value;
    }

    /**
     * Gets the value of the run1500M property.
     * 
     */
    public float getRun1500M() {
        return run1500M;
    }

    /**
     * Sets the value of the run1500M property.
     * 
     */
    public void setRun1500M(float value) {
        this.run1500M = value;
    }

}
